config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tests do
    resources :finals
    resources :results
  end
  root 'home#index'

  devise_for :users, controllers: {
    registrations: "registrations"
  }
  
  resources :students
# config/routes.rb
  resources :assignments
  resources :tests do
    resources :questions do
      resources :options
    end
    resources :blanks
    resources :truefalses
  end

  resources :tests do
    resources :submits do
      resources :attempts
    end
  end

  namespace :api do
    namespace :v1 do
      resources :tests
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    belongs_to :user
    belongs_to :test
end

app/models/attempt.rb
class Attempt < ApplicationRecord
    belongs_to :test
    belongs_to :submit
    belongs_to :user
end

app/models/blank.rb
class Blank < ApplicationRecord
    belongs_to :test
    validates :blank, presence: true, format: { with: /__blank__/ }
    has_many :submits , dependent: :destroy
end

app/models/final.rb
class Final < ApplicationRecord
    # has_many :submits , dependent: :destroy
    belongs_to :user
    belongs_to :test
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question

  validates :option_key, length: { maximum: 1, message: "Option key must be one character long" }
  validates :option_key, uniqueness: { scope: :question_id, message: "Option key already exists for this question" }
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :options , dependent: :destroy
    has_many :submits , dependent: :destroy
    belongs_to :test
end

app/models/result.rb
class Result < ApplicationRecord
    belongs_to :user
    belongs_to :test
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/submit.rb
class Submit < ApplicationRecord
    # belongs_to :question
    belongs_to :user 
    belongs_to :test
    # belongs_to :blank
    belongs_to :question, optional: true
    belongs_to :blank, optional: true
    belongs_to :truefalse, optional: true
    # belongs_to :final
    has_many :attempts
end

app/models/test.rb
class Test < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :submits
    has_many :assignments, dependent: :destroy
    belongs_to :user
    has_many :blanks, dependent: :destroy
    has_many :truefalse, dependent: :destroy
    has_many :finals
    has_many :results
    has_many :attempts
  
    def self.ransackable_associations(auth_object = nil)
      %w[questions submits assignments blanks truefalse finals results attempts user]
      # Add all associations that you want to be searchable here
    end
  end
  

app/models/truefalse.rb
class Truefalse < ApplicationRecord
    belongs_to :test
    has_many :submits , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true
  has_one_attached :image
  has_many :submits
  scope :admins, -> { where(role: 'admin') }
  scope :normalUsers, -> { where(role: 'user') }
  has_many :assignments , dependent: :destroy
  has_many :tests
  has_many :finals
  has_many :results
  has_many :attempts
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
  before_action :set_question, only: [:edit, :update, :show, :destroy]
  before_action :set_test, only: [:edit, :update, :show, :destroy, :new, :create, :index]
  before_action :validate_creator, only: [:edit, :update, :show, :destroy, :new, :create, :index]

  def index
    @questions = @test.questions.all
    @users = User.normalUsers
    @submits = Submit.where(test_id: @test.id)
    render json: @questions ,include: [:options, :submits]
  end

  def create
    @question = @test.questions.build(question_params)
    if @question.save
      render json: @question, status: :created, location: edit_test_question_path(@test, @question)
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def new
    @question = @test.questions.build
  end

  def show
    render json: @question
  end

  def update
    if @question.update(question_params)
      render json: @question, status: :ok, location: edit_test_question_path(@test, @question)
    else
      render json: @question.errors, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @question.destroy
    render json: { notice: "Question destroyed :(" }
  end

  private

  def question_params
    params.require(:question).permit(:title, :entered_answer, :correct_option, :test_id, :marks)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_test
    @test = Test.find(params[:test_id])
  end

  def validate_creator
    unless @test.user_id == current_user.id
      render json: { error: "You are not the valid author!" }, status: :unauthorized
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:edit, :update, :show, :destroy]
  before_action :set_test, only: [:edit, :update, :show, :destroy, :new, :create, :index]
  before_action :validate_creator, only: [:edit, :update, :show, :destroy, :new, :create, :index]

  def index
    @questions = @test.questions.all
    @users = User.normalUsers
    @submits = Submit.where(test_id: @test.id) 
  end
  
  def create
    @question = @test.questions.build(question_params)
    if @question.save
      redirect_to edit_test_question_path(@test, @question)
    else
      render "new"
    end
  end
  

  def new
    @question = @test.questions.build
  end

  def show
    @submits = Submit.where(test_id: @test.id) 
  end

  def update
    if @question.update(question_params)
      redirect_to edit_test_question_path(@test, @question) # Use @test to redirect to test's question
    else
      render "edit"
    end
  end

  def edit
  end

  def destroy
    @question.destroy 
    redirect_to test_questions_path(@test), notice: "Question destroyed :("
  end

  private

  def question_params
    params.require(:question).permit(:title, :entered_answer, :correct_option, :test_id , :marks)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_test
    @test = Test.find(params[:test_id])
  end

  def validate_creator
    if @test.user_id != current_user.id
      redirect_to root_path, alert: "You are not the valid author!"
    end
  end

end

app/helpers/blanks_helper.rb
module BlanksHelper
end

app/helpers/falsity_helper.rb
module FalsityHelper
end

app/helpers/finals_helper.rb
module FinalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/questions/edit.html.erb
<div class="link_for_back_button_test_edit" style="position : relative ; top : 3rem; left: 2rem;">
  <%= link_to test_questions_path(@test) ,style: " margin-right: 1rem; color : black; margin-top : -.4rem;" do%>
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
    </svg>
  <%end%>
</div>
<div class="outer_div_for_question_edit_path">
  <div class="top_heading_for_edit_question">
    Edit the Question
  </div>
  <div class="bottom_div_for_the_form_of_option_and_question">
    <div class="left_side_form_for_the_question_div">
      <div class="top_heading_for_left_side_form_for_the_question_div">
        Question
      </div>
      <%= form_with(model: [@test, @question], url: test_question_path(@test, @question), method: :patch) do |f| %>
        <div class="question_update_input_div_for_single">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>
        <div class="question_update_input_div_for_single">
          <%= f.label :marks %>
          <%= f.number_field :marks, placeholder: "Enter marks for Question", min: 1 %>
        </div>
        <% if @question.options.count >= 2 %>
          <% if !@question.correct_option.present? %>
            <p class="alert alert-danger">Please Select Correct Option.</p>
          <% end %>
          <div class="choose_correct_option_from_user_div">
            <%= f.label :correct_option %>
            <%= f.collection_select :correct_option, @question.options, :id, :option_key , prompt: "Select an Correct Option"%>
          </div>
        <% else %>
          <p class="alert alert-danger">Add Atleast 2 Options to Choose Correct Answer.</p>
        <% end %>
        <div>
          <%= f.submit "Submit" , class: "btn btn-success" ,style:"position : relative; left : 50%; transform :translate(-50%); margin-top : 1rem;"%>
        </div>
      <% end %>
    </div>
    <div class="left_side_form_for_the_question_div">
      <div class="top_heading_for_left_side_form_for_the_question_div">
        Options
      </div>
      
      <% if @question.options.count > 0 %>
        <% @question.options.each do |option| %>
          <div style="display: flex; justify-content: space-between; align-items : center; margin : .5rem 0;">
            <div class="single_option_for_single_question_div_index">
              <div class="option_key_display_for_single_option">
                <%= "#{option.option_key} : " %>
              </div>
              <div class="option_text_display_for_single_option">
                <%= option.option_text %>
              </div>
            </div>
            <div class="buttons_div_for_opitions_edit_question">
              <%= link_to "Edit" , edit_test_question_option_path(@test , @question , option) , class: "btn btn-primary"%>
              <%= link_to "Delete" , test_question_option_path(@test , @question , option) , data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } , class: "btn btn-danger"%>
            </div>
          </div>
        <% end %>
      <% else %>
        <p style="text-align : center; font-size : 1.2rem;">No Options Yet!</p>
      <% end %>
    </div>
    <div class="left_side_form_for_the_question_div">
      <div class="top_heading_for_edit_question">
        Create Options
      </div>
      <%= render 'options/form', question: @question %>
    </div>
  </div>

  <div class="display_question_for_edit_model">
    <div class="top_heading_for_edit_question">
      Preview
    </div>
    <div class="single_question_div_for_index_question" style="width: 70%; position: relative; left: 50%; transform: translate(-50%);">
      <div class="title_of_single_question_div_for_question_index">
        <div class="qustion_heading_for_the_index_question">
          Question:
        </div>
        <div class="question_title_for_the_index_question">
          <%= @question.title %>
        </div>
      </div>
      <div class="option_div_for_single_question_index_questions">
        <% if @question.options.present? %>
          <% @question.options.each do |option| %>
            <div class="single_option_for_single_question_div_index">
              <div class="option_key_display_for_single_option">
                <%= "#{option.option_key} : " %>
              </div>
              <div class="option_text_display_for_single_option">
                <%= option.option_text %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="correct_option_div_for_question">
        <div class="correct_option_heading_div">
          Correct Answer:
        </div>
        <div class="correct_answer_title_display_for_question">
          <% if @question.correct_option.present? %>
            <% @correct_option_with_id = Option.find_by(id: @question.correct_option.chomp.to_i) %>
            <% if @correct_option_with_id.present? %>
              <div class="correct_answer_title_display_for_question">
                <%= @correct_option_with_id.option_key %><span style="margin-left : 1rem; font-size : 1.2rem; font-weight : bold;">(<%= @correct_option_with_id.option_text %>)</span>
              </div>
            <% else %>
              <div>Not Added yet!</div>
            <% end %>
          <% else %>
            <div>Not Added yet!</div>
          <% end %>
        </div>
      </div>
      <div class="correct_option_div_for_question">
        <div class="correct_option_heading_div">
          Marks :
        </div>
        <div class="correct_answer_title_display_for_question">
          <% if @question.marks.present? %>
            <%= @question.marks %>
          <% else %>
            <div>Not Added yet!</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<% test_score = 0%>
<% @test.questions.each do |question|%>
  <% if question.marks && question.marks > 0 %>
    <% test_score += question.marks%>
  <% end %>
<% end %>
<% @test.blanks.each do |blank|%>
  <% if blank.marks && blank.marks > 0 %>
    <% test_score += blank.marks%>
  <% end %>
<% end %>
<% @test.truefalse.each do |truefalse|%>
  <% if truefalse.marks && truefalse.marks > 0 %>
    <% test_score += truefalse.marks%>
  <% end %>
<% end %>
<div class="single_test_all_question_div_main"> 
  <div class="top_heading_for_current_question" style="display : flex; justify-content : space-between; align-items : center;">
    <span style="display : flex; align-items :center;">
      <%= link_to test_path(@test) ,style: " margin-right: 1rem; color : black; margin-top : -.4rem;" do%>
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
        </svg>
      <% end%>
      <%= @test.name%>/Questions<span style="margin-left : 1rem; font-size : 1.2rem;">(<%= test_score%> Marks)</span>
    </span>
  </div>
  <%= link_to new_test_question_path, class: "add_new_question_link_for_questions btn btn-success" do %>
    <div class="icon_for_add_new_question_div">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
        <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0"/>
      </svg>
    </div>
    <p>Add new Question</p>
  <% end %>
  <div class="lower_div_for_the_question_index_page">
    <div class="all_question_map_div_for_index_question">
      <% @questions.each_with_index do |question , index| %>
        <div class="single_question_div_for_index_question">
          <div class="title_of_single_question_div_for_question_index">
            <div class="qustion_heading_for_the_index_question">
              Question <%= index+1 %>: 
            </div>
            <div class="qustion_title_for_the_index_question">
              <%= question.title %>
            </div>
          </div>
          <% if question.options.present? %>
            <div class="option_div_for_single_question_index_questions">
              <% question.options.each do |option| %>
                <div class="single_option_for_single_question_div_index">
                  <div class="option_key_display_for_single_option">
                    <%= "#{option.option_key} : " %>
                  </div>
                  <div class="option_text_display_for_single_option">
                    <%= option.option_text %>
                  </div>
                </div>
              <% end %>
            </div>
          <% else %>
            <p class="alert alert-danger">Add Options to the question to display it to the candidates.</p>
          <% end %>
          
          <% if question.correct_option.present? %>
          <div class="correct_option_div_for_question">
            <div class="correct_option_heading_div">
              Correct Answer : 
            </div>
            <div class="correct_answer_title_display_for_question">
              <% @correct_option_with_id = Option.find_by(id: question.correct_option.chomp.to_i) %>
              <% if @correct_option_with_id.present? %>
                <%= @correct_option_with_id.option_key %><span style="margin-left: 1rem; font-size: 1.2rem; font-weight: bold;">(<%= @correct_option_with_id.option_text %>)</span>
              <% else %>
                <p class="alert alert-danger">Correct Answer not found for this question.</p>
              <% end %>
            </div>
          </div>
          <% else %>
            <p class="alert alert-danger">Add the Correct Answer to the quesiton to display it to the candidate.</p>
          <% end %>
          <% if question.marks.present? %>
          <div class="correct_option_div_for_question">
            <div class="correct_option_heading_div">
              Marks : 
            </div>
            <div class="correct_answer_title_display_for_question">
              <%= question.marks %>
            </div>
          </div>
          <% else %>
            <p class="alert alert-danger">Add the Marks to the quesiton to display it to the candidate.</p>
          <% end %>
          <div class="link_for_action_of_question">
            <%= link_to "Edit", edit_test_question_path(@test, question) , class: "btn btn-primary" %>
            <%= link_to "Delete", test_question_path(@test, question) , data: {turbo_method: :delete , turbo_confirm: 'Are you sure?' } , class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<%#  same css for quesiton then test is the class name included %>
<div class="outer_div_form_for_test_creation">
  <div class="inner_div_for_the_test_creation">
    <div class="top_heading_for_test_creation">
      Create a new Question
    </div>
    <%= form_with(model: @test.questions.build, url: test_questions_path(@test)) do |f| %>
      <div class="inner_form_div_test_creation">
        <%= f.label :title %>
        <%= f.text_field :title , required: :true%>
      </div>
      <%= f.submit "Next" , class: "submit_button_for_test_creation btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<%# <%= @question.title%>
<%# <% @question.options.each do |option|
  <%# <div>
    <%# <%= option.option_key
    <%# <%= option.option_text
  <%# </div>
<%# <% end
<%# 
<%# <%= render 'options/form', question: @question
<%# 
<%# <% if @question.options.count >= 2
  <%# <%= form_with(model: [@test, @question], url: test_question_path(@test, @question), method: :patch) do |f|
    <%# <div>
      <%# <%= f.label :correct_option
      <%# <%= f.collection_select :correct_option, @question.options, :option_key, :option_key
    <%# </div>
<%# 
    <%# <div>
      <%# <%= f.submit "Submit"
    <%# </div>
  <%# <% end
  <%# <% else
    <%# <p>Add Atleast 2 Options to Choose Correct Answer.</p>
<%# <% end
<%# <div>