config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tests do
    resources :finals
    resources :results
  end
  root 'home#index'

  devise_for :users, controllers: {
    registrations: "registrations"
  }
  
  resources :students
# config/routes.rb
  resources :assignments
  resources :tests do
    resources :questions do
      resources :options
    end
    resources :blanks
    resources :truefalses
  end

  resources :tests do
    resources :submits do
      resources :attempts
    end
  end

  namespace :api do
    namespace :v1 do
      resources :tests
    end
  end

end

app/models/submit.rb
class Submit < ApplicationRecord
    # belongs_to :question
    belongs_to :user 
    belongs_to :test
    # belongs_to :blank
    belongs_to :question, optional: true
    belongs_to :blank, optional: true
    belongs_to :truefalse, optional: true
    # belongs_to :final
    has_many :attempts
end

app/controllers/api/v1/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :set_test
  before_action :set_submit, only: [:show, :edit, :update, :destroy]

  def index
    @submits = @test.submits
    render json: @submits
  end

  def new
    @submit = @test.submits.new
    @questions = @test.questions.all
    @blanks = @test.blanks.all
    @truefalses = @test.truefalse.all
    @submits = current_user.submits.where(test_id: @test.id)
  end

  def create
    submitted_answers = submit_params[:answers] || {}
    submitted_blanks = submit_params[:blanks] || {}
    submitted_truefalses = submit_params[:truefalses] || {}

    if submitted_answers.present? || submitted_blanks.present? || submitted_truefalses.present?
      submitted_answers.each do |question_id, option_id|
        @test.submits.create!(
          user_id: current_user.id,
          question_id: question_id,
          option_id: option_id
        )
      end

      submitted_blanks.each do |blank_id, entered_blank|
        @test.submits.create!(
          user_id: current_user.id,
          blank_id: blank_id,
          entered_blank: entered_blank
        )
      end

      submitted_truefalses.each do |truefalse_id, entered_state|
        @test.submits.create!(
          user_id: current_user.id,
          truefalse_id: truefalse_id,
          entered_state: entered_state
        )
      end

      redirect_to new_test_submit_path(@test), notice: 'Answers submitted successfully.'
    else
      redirect_to new_test_submit_path(@test), alert: 'No answers submitted.'
    end
  end

  def show
  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_submit
    @submit = @test.submits.find(params[:id])
  end

  def submit_params
    params.require(:submit).permit(
      :user_id,
      :entered_answer,
      :question_id,
      :option_id,
      { answers: {} },
      { blanks: {} },
      { truefalses: {} },
      :blank_id,
      :entered_blank,
      :truefalse_id,
      :entered_state
    )
  end
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :set_test
  before_action :set_submit, only: [:show, :edit, :update, :destroy]

  def index
    user_id = params[:user_id]
    @user = User.find_by(id: user_id)
    @submits = @test.submits.where(test_id: @test.id, user_id: user_id)
    @result = @test.results.find_by(user_id: @user.id)
  end
  
  def new
    @submit = @test.submits.new
    @questions = @test.questions.all
    @blanks = @test.blanks.all
    @truefalses = @test.truefalse.all
    @result = @test.results.find_by(user_id: current_user.id)
    @submits = current_user.submits.where(test_id: @test.id)
    test_questions_count = @test.questions.count
    test_blanks_count = @test.blanks.count
    test_truefalse_count = @test.truefalse.count
    @test_all_enteries = test_questions_count + test_blanks_count + test_truefalse_count
  end

  def create
    submitted_answers = submit_question_params[:answers] || {}
    submitted_blanks = submit_blank_params[:blanks] || {}
    submitted_truefalses = submit_truefalse_params[:truefalses] || {}

    if submitted_answers.present? || submitted_blanks.present? || submitted_truefalses.present?
      submitted_answers.each do |question_id, option_id, trail|
        @test.submits.create!(
          user_id: current_user.id,
          question_id: question_id,
          option_id: option_id,
          trail: trail
        )
      end

      submitted_blanks.each do |blank_id, entered_blank|
        @test.submits.create!(
          user_id: current_user.id,
          blank_id: blank_id,
          entered_blank: entered_blank
        )
      end

      submitted_truefalses.each do |truefalse_id, entered_state|
        @test.submits.create!(
          user_id: current_user.id,
          truefalse_id: truefalse_id,
          entered_state: entered_state
        )
      end

      redirect_to new_test_submit_path(@test), notice: 'Answers submitted successfully.'
    else
      redirect_to new_test_submit_path(@test), alert: 'No answers submitted.'
    end
  end

  def show
  end

  def edit
    
  end

  def update

  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_submit
    @submit = @test.submits.find(params[:id])
  end

  def submit_question_params
    params.require(:submit).permit(
      :user_id,
      :question_id,
      :option_id,
      { answers: {} },
      :trail
    )
  end
  def submit_blank_params
    params.require(:submit).permit(
      :user_id,
      { blanks: {} },
      :blank_id,
      :entered_blank,
      :trail
    )
  end
  def submit_truefalse_params
    params.require(:submit).permit(
      :user_id,
      { truefalses: {} },
      :truefalse_id,
      :entered_state, 
      :trail
    )
  end
end

app/views/submits/index.html.erb
<% question_score = 0%>
<% truefalse_score = 0 %>
<% blanks_score = 0%>
<% question_obtained_score = 0%>
<% blank_obtained_score = 0%>
<% truefalse_obtained_score = 0%>
<% @test.questions.each do |question|%>
  <% if question.marks && question.marks > 0 %>
    <% question_score += question.marks%>
  <% end %>
<% end %>
<% @test.blanks.each do |blank|%>
  <% if blank.marks && blank.marks > 0 %>
    <% blanks_score += blank.marks%>
  <% end %>
<% end %>
<% @test.truefalse.each do |truefalse| %>
  <% if truefalse.marks && truefalse.marks > 0 %>
    <% truefalse_score += truefalse.marks %>
  <% end %>
<% end %>
<% total_test_score = question_score + blanks_score + truefalse_score%>

<div class="main_div_for_take_test_div_submit">
  <div class="top_heading_for_current_question" style="display : flex; align-items : center; justify-content : center;">
    <%= @test.name %><span style="margin-left : 1rem; font-size : 1.2rem;">(<%= total_test_score%> Marks)</span>
  </div>
  <div class="user_by_whome_submitted btn btn-success" style="display : flex; align-items : center; justify-content : center; margin : 0 2rem;">
    <h3>
       Submitted by <%= @user.name%>
    </h3>
  </div>
</div>
<% result_extract = @user.results.find_by(test_id: @test.id)%>
<% if result_extract.present? %>
  <% if result_extract.status == true %>
    <div style="margin : 1rem 2rem;">
      <div class="alert alert-success" style="font-size : 1.2rem; font-weight : bold;"><%= @user.name%> has passed the test successfully.</div>
      <div style="display : flex; margin : 1rem 0 ; align-items : center;" class="alert alert-info">
        Change the Status for the User
        <%= form_with(model: @result , url: test_result_path(@test, id: result_extract.id), method: :patch) do |form|%>
          <div>
            <%= form.hidden_field :test_id , value: @test.id%>
            <%= form.hidden_field :user_id , value: @user.id%>
            <%= form.hidden_field :status , value: true%>
            <%= form.hidden_field :retake , value: false %>
            <%= form.submit "Pass" , class: "btn btn-success" , style: "margin : 0 1rem;"%>
          </div>
        <% end %>
        <%= form_with(model: @result , url: test_result_path(@test, id: result_extract.id), method: :patch) do |form|%>
        <div>
            <%= form.hidden_field :test_id , value: @test.id%>
            <%= form.hidden_field :user_id , value: @user.id%>
            <%= form.hidden_field :status , value: false%>
            <%= form.hidden_field :retake , value: false%>
            <%= form.submit "Fail" , class: "btn btn-danger"%>
          </div>
        <% end %>
      </div>
    </div>
  <%else%>
    <div style="margin : 1rem 2rem;">
      <div class="alert alert-danger" style="font-size : 1.2rem; font-weight : bold; display : flex;">
        <%= @user.name%> have failed the test,
      </div>
        <div style="display : flex; margin : 1rem 0 ; align-items : center;" class="alert alert-info">
          Change the Status for the User
          <%= form_with(model: @result , url: test_result_path(@test, id: result_extract.id), method: :patch) do |form|%>
            <div>
              <%= form.hidden_field :test_id , value: @test.id%>
              <%= form.hidden_field :user_id , value: @user.id%>
              <%= form.hidden_field :status , value: true%>
              <%= form.hidden_field :retake , value: false %>
              <%= form.submit "Pass" , class: "btn btn-success" , style: "margin : 0 1rem;"%>
            </div>
          <% end %>
          <%= form_with(model: @result , url: test_result_path(@test, id: result_extract.id), method: :patch) do |form|%>
          <div>
              <%= form.hidden_field :test_id , value: @test.id%>
              <%= form.hidden_field :user_id , value: @user.id%>
              <%= form.hidden_field :status , value: false%>
              <%= form.hidden_field :retake , value: false%>
              <%= form.submit "Fail" , class: "btn btn-danger"%>
            </div>
          <% end %>
        </div>
    </div>
  <% end %>
<% else %>
  <div style="display : flex; margin : 1rem 2rem ; align-items : center;" class="alert alert-info">
    Mark the Status for the User
    <%= form_with(model: Result.new , url: test_results_path(@test, user_id: @user.id), method: :post) do |form|%>
      <div>
        <%= form.hidden_field :test_id , value: @test.id%>
        <%= form.hidden_field :user_id , value: @user.id%>
        <%= form.hidden_field :status , value: true%>
        <%= form.hidden_field :retake , value: false %>
        <%= form.submit "Pass" , class: "btn btn-success" , style: "margin : 0 1rem;"%>
      </div>
    <% end %>
    <%= form_with(model: Result.new , url: test_results_path(@test, user_id: @user.id), method: :post) do |form|%>
      <div>
        <%= form.hidden_field :test_id , value: @test.id%>
        <%= form.hidden_field :user_id , value: @user.id%>
        <%= form.hidden_field :status , value: false%>
        <%= form.hidden_field :retake , value: false%>
        <%= form.submit "Fail" , class: "btn btn-danger"%>
      </div>
    <% end %>
  </div>
<% end %>
<% if @submits.present? %>
  <% @submits.each_with_index do |submit| %>
    <% question_submits = @test.questions.where(id: submit.question_id) %>
    <% blank_submits = @test.blanks.where(id: submit.blank_id) %>
    <% truefalse_submits = @test.truefalse.where(id: submit.truefalse_id) %>
    <% if question_submits.present? && submit.question_id.present? && submit.option_id.present? %>
      <div class="question_div_for_submit_show">
        <% question_submits.each_with_index do |question_submit| %>
            <div class="single_div_for_questioN_submit_sindex">
                <div class="questioN_title_div_for_the_submit_index">
                    <strong>Question : </strong><%= question_submit.title %><strong style="margin-left : 1rem; font-size : 1rem;">(<%= question_submit.marks%> Marks)</strong>
                </div>
                <% correct_answer = question_submit.options.find_by(id: question_submit.correct_option.chomp.to_i) %>
                <div class="correct_answer_div_for_submit_show">
                    Correct Answer : <%= correct_answer.option_text %>
                </div>
                <% submitted_answer = question_submit.options.find_by(id: submit.option_id) %>
                <div class="submitted_answer_div_for_submit_show">
                    Submitted Answer : <%= submitted_answer.option_text %>
                </div>
                <% if correct_answer.id == submitted_answer.id %>
                    <h5 style="color : green; font-size : 1.2rem; font-weight : bold;">Score obtianed in this Question are <%=question_submit.marks%></h5>
                    <% question_obtained_score += question_submit.marks%>
                <% else %>
                    <h5 style="color :red; font-size : 1.2rem; font-weight : bold;">Score obtianed in this Question are 0.</h5>
                <% end %>
            </div>
        <% end %>
      </div>
    <% end %>            
    <% if blank_submits.present? %>
      <div class="question_div_for_submit_show">
        <% blank_submits.each do |blank_submit| %>
            <div class="single_div_for_questioN_submit_sindex">
                <div class="questioN_title_div_for_the_submit_index">
                    <strong>Blank : </strong><%= blank_submit.blank %> <strong style="margin-left : 1rem; font-size : 1rem;">(<%= blank_submit.marks%> Marks)</strong>
                </div>
                <div class="correct_answer_div_for_submit_show">
                    Correct Answer : <%= blank_submit.correct_blank %>
                </div>
                <div class="submitted_answer_div_for_submit_show">
                    Submitted Answer : <%= submit.entered_blank %>
                </div>
                <% if blank_submit.correct_blank == submit.entered_blank %>
                    <h5 style="color : green; font-size : 1.2rem; font-weight : bold;">Score obtianed in this Question are <%=blank_submit.marks%></h5>
                    <% blank_obtained_score += blank_submit.marks%>
                <% else %>
                    <h5 style="color :red; font-size : 1.2rem; font-weight : bold;">Score obtianed in this Question are 0.</h5>
                <% end %>
            </div>
        <% end %>
      </div>
    <% end %>
    <% if truefalse_submits.present? %>
    <div class="question_div_for_submit_show">
        <% truefalse_submits.each do |truefalse_submit| %>
            <div class="single_div_for_questioN_submit_sindex">
                <div class="questioN_title_div_for_the_submit_index">
                    <strong>True/False: </strong><%= truefalse_submit.statement %> <strong style="margin-left : 1rem; font-size : 1rem;">(<%= truefalse_submit.marks%> Marks)</strong>
                </div>
                <div class="correct_answer_div_for_submit_show">
                    Correct Answer: 
                    <span><%= truefalse_submit.state %></span>
                </div>
                <div class="submitted_answer_div_for_submit_show">
                    Submitted Answer:
                    <span><%= submit.entered_state %></span>
                </div>
                <% if truefalse_submit.state == submit.entered_state %>
                    <h5 style="color : green; font-size : 1.2rem; font-weight : bold;">Score obtianed in this Question are <%=truefalse_submit.marks%></h5>
                    <% truefalse_obtained_score += truefalse_submit.marks%>
                <% else %>
                    <h5 style="color :red; font-size : 1.2rem; font-weight : bold;">Score obtianed in this Question are 0.</h5>
                <% end %>
            </div>
        <% end %>
    </div>
    <% end %>
  <% end %>
<% else %>
  <p>
    <h1 style="text-align : center;">
      No submits yet
    </h1>
  </p>
<% end %>
<div class="lower_socre_for_each_submtion_test">
  <h2 style="text-align : center; margin-top : 1rem;">Total Marks</h2>
  <% total_obtained_score = question_obtained_score + blank_obtained_score + truefalse_obtained_score%>
  <button class="alert alert-info" style=" width :100%; font-size : 1.6rem;">Obtained Marks <strong><%= total_obtained_score%></strong> / <%= total_test_score%></button>
</div>