config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :tests do
    resources :finals
    resources :results
  end
  root 'home#index'

  devise_for :users, controllers: {
    registrations: "registrations"
  }
  
  resources :students
# config/routes.rb
  resources :assignments
  resources :tests do
    resources :questions do
      resources :options
    end
    resources :blanks
    resources :truefalses
  end

  resources :tests do
    resources :submits do
      resources :attempts
    end
  end

  namespace :api do
    namespace :v1 do
      resources :tests
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/assignment.rb
class Assignment < ApplicationRecord
    belongs_to :user
    belongs_to :test
end

app/models/attempt.rb
class Attempt < ApplicationRecord
    belongs_to :test
    belongs_to :submit
    belongs_to :user
end

app/models/blank.rb
class Blank < ApplicationRecord
    belongs_to :test
    validates :blank, presence: true, format: { with: /__blank__/ }
    has_many :submits , dependent: :destroy
end

app/models/final.rb
class Final < ApplicationRecord
    # has_many :submits , dependent: :destroy
    belongs_to :user
    belongs_to :test
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question

  validates :option_key, length: { maximum: 1, message: "Option key must be one character long" }
  validates :option_key, uniqueness: { scope: :question_id, message: "Option key already exists for this question" }
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :options , dependent: :destroy
    has_many :submits , dependent: :destroy
    belongs_to :test
end

app/models/result.rb
class Result < ApplicationRecord
    belongs_to :user
    belongs_to :test
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/submit.rb
class Submit < ApplicationRecord
    # belongs_to :question
    belongs_to :user 
    belongs_to :test
    # belongs_to :blank
    belongs_to :question, optional: true
    belongs_to :blank, optional: true
    belongs_to :truefalse, optional: true
    # belongs_to :final
    has_many :attempts
end

app/models/test.rb
class Test < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :submits
    has_many :assignments, dependent: :destroy
    belongs_to :user
    has_many :blanks, dependent: :destroy
    has_many :truefalse, dependent: :destroy
    has_many :finals
    has_many :results
    has_many :attempts
  
    def self.ransackable_associations(auth_object = nil)
      %w[questions submits assignments blanks truefalse finals results attempts user]
      # Add all associations that you want to be searchable here
    end
  end
  

app/models/truefalse.rb
class Truefalse < ApplicationRecord
    belongs_to :test
    has_many :submits , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true
  has_one_attached :image
  has_many :submits
  scope :admins, -> { where(role: 'admin') }
  scope :normalUsers, -> { where(role: 'user') }
  has_many :assignments , dependent: :destroy
  has_many :tests
  has_many :finals
  has_many :results
  has_many :attempts
end

app/helpers/blanks_helper.rb
module BlanksHelper
end

app/helpers/falsity_helper.rb
module FalsityHelper
end

app/helpers/finals_helper.rb
module FinalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Home" , root_path , class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%if current_user.role == "super admin" || current_user.role == "admin"%>
          <li class="nav-item">
            <%= link_to "Create Members" , new_student_path , class: "nav-link active"%>
          </li>
        <%end%>
        <li class="nav-item">
          <%# <%= link_to "Question", questions_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%# <%= link_to "Solve" , submits_path , class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Test Session" , tests_path , class: "nav-link active"%>
        </li>
        <%if current_user.role == "super admin" || current_user.role == "admin"%>
        <li class="nav-item">
          <%= link_to "View API" , api_v1_tests_path , class: "nav-link active"%>
        </li>
          <li class="nav-item">
            <%= link_to "Assign" , assignments_path , class: "nav-link active"%>
          </li>
        <%end%>
      </ul>
      <form class="d-flex" role="search">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item nav-link active">
              Hello, <%= current_user.name%>
            </li>
            <li class="nav-item">
              <%= link_to "Log Out" , destroy_user_session_path	, data: {turbo_method: :delete} , class: "nav-link active"%>
            </li>
        </ul>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" href="https://cdn.iconscout.com/icon/free/png-256/free-quiz-4039217-3354814.png" type="image/x-icon">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head> 

  <body>

    <% if user_signed_in? %>
      <%= render 'layouts/header' %>
    <% end %>
    <% if flash[:notice].present? %>
      <div class="alert alert-info" style="margin-bottom: -16px;"> 
        <%= notice %>
      </div>
    <% end %>
    <% if flash.now[:alert].present? %>
      <div class="alert alert-danger" style="margin-bottom: -16px;">
        <%= flash.now[:alert] %>
      </div>
    <% end %>

    
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>